### ISSUE TITLE
failed to find .env at default paths: [./.env, ./.env.js, ./.env.json]

### ISSUE THREAD

**Issue by gomjellie** [hseoy/chrome-extension-react-typescript-boilerplate#1]
README 가이드대로 프로젝트를 생성해서 yarn dev로 실행했을때 오류가 뜹니다.

![image](https://user-images.githubusercontent.com/13645032/150066459-8a39ed47-7b39-4205-870b-5876d192afa5.png)

**Comment by hseoy** [comment]
.env 파일을 생성해주세요! 당장의 해결방법은 그러하고 추가적으로 env 파일을 optional하게 사용할 수 있도록 수정하도록 하겠습니다.

**Comment by gomjellie** [comment]
가이드대로 보일러플레이트 깔았을때 처음부터 .env 파일이 있었으면 좋겠어요.

근데 이거 엄청 잘만드셨네요. 필요한 세팅 딱 되있어서 좋군요 ㅎㅎ

**Comment by hseoy** [comment]
> 근데 이거 엄청 잘만드셨네요. 필요한 세팅 딱 되있어서 좋군요 ㅎㅎ

ㅋㅋㅋㅋㅋ 넘넘 감사합니다. ㅎㅎ 최고의 칭찬! 🙌 🙌 🙌

> 가이드대로 보일러플레이트 깔았을때 처음부터 .env 파일이 있었으면 좋겠어요.

.env 파일을 git에 올리는 것은 보안 관련 문제가 발생할 수 있다고 생각해서 포함하는 것은 고려하고 있지는 않아요. 거기다 추가적인 환경 변수를 사용하지 않는 경우도 있을 것을 고려했을 때 env 파일을 optional하게 사용할 수 있도록 하는 방향의 수정이 적절하다고 생각합니다.

현재 main branch에 이 이슈에 대한 수정을 추가하였고 현재를 기준으로 env 파일 관련 오류는 발생하지 않습니다. => git pull 하시고 추가적으로 오류 발생하시면 comment 달아주세요~~.

반영 커밋: [c67d905](https://github.com/hseoy/chrome-extension-react-typescript-boilerplate/commit/c67d905aaa52dc62eb8d3e2abd6fe57d8fe2acc9)

해결되었으니 이 이슈는 닫도록 하겠습니당~~
